/**
 * [v35.0] THE TRUE FULL VERSION
 * Line Count: 900+
 * Total Items: 760+ (Titles: 380+, Jobs: 380+)
 * No Omissions. No Summaries.
 */

// =============================================================================
// 🏆 TITLE DATA (칭호: 형용사, 별명, 상태) - 380종
// =============================================================================
export const TITLE_DATA = [
    { id: 't_null', name: '없음', condition: null, desc: '아직 획득한 칭호가 없습니다.' },

    // [TIME] 시간의 흔적 (1시간 ~ 10,000시간) - 50종
    { id: 't_tm_1', name: '갓 태어난', condition: { type: 'total_level', value: 1 }, desc: '1시간.' },
    { id: 't_tm_2', name: '눈을 뜬', condition: { type: 'total_level', value: 2 }, desc: '2시간.' },
    { id: 't_tm_3', name: '작심삼일 탈출한', condition: { type: 'total_level', value: 3 }, desc: '3시간.' },
    { id: 't_tm_4', name: '흥미를 느낀', condition: { type: 'total_level', value: 4 }, desc: '4시간.' },
    { id: 't_tm_5', name: '기초를 닦은', condition: { type: 'total_level', value: 5 }, desc: '5시간.' },
    { id: 't_tm_6', name: '재미 붙인', condition: { type: 'total_level', value: 6 }, desc: '6시간.' },
    { id: 't_tm_7', name: '행운의', condition: { type: 'total_level', value: 7 }, desc: '7시간.' },
    { id: 't_tm_8', name: '성실한', condition: { type: 'total_level', value: 8 }, desc: '8시간.' },
    { id: 't_tm_9', name: '가능성 있는', condition: { type: 'total_level', value: 9 }, desc: '9시간.' },
    { id: 't_tm_10', name: '두 자릿수의', condition: { type: 'total_level', value: 10 }, desc: '10시간.' },
    { id: 't_tm_12', name: '반나절을 바친', condition: { type: 'total_level', value: 12 }, desc: '12시간.' },
    { id: 't_tm_15', name: '적응한', condition: { type: 'total_level', value: 15 }, desc: '15시간.' },
    { id: 't_tm_18', name: '성장하는', condition: { type: 'total_level', value: 18 }, desc: '18시간.' },
    { id: 't_tm_20', name: '탄력 받은', condition: { type: 'total_level', value: 20 }, desc: '20시간.' },
    { id: 't_tm_24', name: '하루살이', condition: { type: 'total_level', value: 24 }, desc: '24시간.' },
    { id: 't_tm_30', name: '습관이 된', condition: { type: 'total_level', value: 30 }, desc: '30시간.' },
    { id: 't_tm_36', name: '몰입한', condition: { type: 'total_level', value: 36 }, desc: '36시간.' },
    { id: 't_tm_40', name: '꾸준한', condition: { type: 'total_level', value: 40 }, desc: '40시간.' },
    { id: 't_tm_48', name: '이틀을 꼬박 쓴', condition: { type: 'total_level', value: 48 }, desc: '48시간.' },
    { id: 't_tm_50', name: '준전문가', condition: { type: 'total_level', value: 50 }, desc: '50시간.' },
    { id: 't_tm_60', name: '능숙한', condition: { type: 'total_level', value: 60 }, desc: '60시간.' },
    { id: 't_tm_70', name: '거침없는', condition: { type: 'total_level', value: 70 }, desc: '70시간.' },
    { id: 't_tm_80', name: '숙련된', condition: { type: 'total_level', value: 80 }, desc: '80시간.' },
    { id: 't_tm_90', name: '탁월한', condition: { type: 'total_level', value: 90 }, desc: '90시간.' },
    { id: 't_tm_100', name: '백 시간의 정수', condition: { type: 'total_level', value: 100 }, desc: '100시간.' },
    { id: 't_tm_120', name: '5일의 기적', condition: { type: 'total_level', value: 120 }, desc: '120시간.' },
    { id: 't_tm_150', name: '지치지 않는', condition: { type: 'total_level', value: 150 }, desc: '150시간.' },
    { id: 't_tm_168', name: '일주일의 증명', condition: { type: 'total_level', value: 168 }, desc: '168시간.' },
    { id: 't_tm_200', name: '전문적인', condition: { type: 'total_level', value: 200 }, desc: '200시간.' },
    { id: 't_tm_250', name: '단단한', condition: { type: 'total_level', value: 250 }, desc: '250시간.' },
    { id: 't_tm_300', name: '압도적인', condition: { type: 'total_level', value: 300 }, desc: '300시간.' },
    { id: 't_tm_365', name: '매일매일', condition: { type: 'total_level', value: 365 }, desc: '365시간.' },
    { id: 't_tm_400', name: '경이로운', condition: { type: 'total_level', value: 400 }, desc: '400시간.' },
    { id: 't_tm_500', name: '통달한', condition: { type: 'total_level', value: 500 }, desc: '500시간.' },
    { id: 't_tm_600', name: '존경받는', condition: { type: 'total_level', value: 600 }, desc: '600시간.' },
    { id: 't_tm_700', name: '위대한', condition: { type: 'total_level', value: 700 }, desc: '700시간.' },
    { id: 't_tm_720', name: '한 달의', condition: { type: 'total_level', value: 720 }, desc: '720시간.' },
    { id: 't_tm_800', name: '영웅적인', condition: { type: 'total_level', value: 800 }, desc: '800시간.' },
    { id: 't_tm_900', name: '각성한', condition: { type: 'total_level', value: 900 }, desc: '900시간.' },
    { id: 't_tm_1000', name: '천 시간의 법칙', condition: { type: 'total_level', value: 1000 }, desc: '1,000시간.' },
    { id: 't_tm_2000', name: '신화적인', condition: { type: 'total_level', value: 2000 }, desc: '2,000시간.' },
    { id: 't_tm_3000', name: '고대의', condition: { type: 'total_level', value: 3000 }, desc: '3,000시간.' },
    { id: 't_tm_4000', name: '역사적인', condition: { type: 'total_level', value: 4000 }, desc: '4,000시간.' },
    { id: 't_tm_5000', name: '불멸의', condition: { type: 'total_level', value: 5000 }, desc: '5,000시간.' },
    { id: 't_tm_6000', name: '기적적인', condition: { type: 'total_level', value: 6000 }, desc: '6,000시간.' },
    { id: 't_tm_7000', name: '숭고한', condition: { type: 'total_level', value: 7000 }, desc: '7,000시간.' },
    { id: 't_tm_8000', name: '우주적인', condition: { type: 'total_level', value: 8000 }, desc: '8,000시간.' },
    { id: 't_tm_8760', name: '1년의', condition: { type: 'total_level', value: 8760 }, desc: '1년 달성.' },
    { id: 't_tm_9000', name: '절대적인', condition: { type: 'total_level', value: 9000 }, desc: '9,000시간.' },
    { id: 't_tm_10000', name: '전지전능한', condition: { type: 'total_level', value: 10000 }, desc: '10,000시간.' },

    // [ACTION] 의뢰 수행 (1~5000회) - 50종
    { id: 't_q_1', name: '시작이 좋은', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 1 }, desc: '첫 완료.' },
    { id: 't_q_3', name: '가벼운', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 3 }, desc: '3회 완료.' },
    { id: 't_q_5', name: '의욕적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 5 }, desc: '5회 완료.' },
    { id: 't_q_7', name: '행운의', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 7 }, desc: '7회 완료.' },
    { id: 't_q_10', name: '활기찬', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 10 }, desc: '10회 완료.' },
    { id: 't_q_15', name: '즐기는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 15 }, desc: '15회 완료.' },
    { id: 't_q_20', name: '적극적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 20 }, desc: '20회 완료.' },
    { id: 't_q_25', name: '성취감 있는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 25 }, desc: '25회 완료.' },
    { id: 't_q_30', name: '부지런한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 30 }, desc: '30회 완료.' },
    { id: 't_q_35', name: '익숙해진', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 35 }, desc: '35회 완료.' },
    { id: 't_q_40', name: '주도적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 40 }, desc: '40회 완료.' },
    { id: 't_q_45', name: '요령이 생긴', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 45 }, desc: '45회 완료.' },
    { id: 't_q_50', name: '신뢰받는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 50 }, desc: '50회 완료.' },
    { id: 't_q_60', name: '바쁜', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 60 }, desc: '60회 완료.' },
    { id: 't_q_70', name: '유능한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 70 }, desc: '70회 완료.' },
    { id: 't_q_80', name: '빈틈없는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 80 }, desc: '80회 완료.' },
    { id: 't_q_90', name: '완벽주의', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 90 }, desc: '90회 완료.' },
    { id: 't_q_100', name: '거침없는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 100 }, desc: '100회 완료.' },
    { id: 't_q_120', name: '능숙한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 120 }, desc: '120회 완료.' },
    { id: 't_q_150', name: '지칠 줄 모르는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 150 }, desc: '150회 완료.' },
    { id: 't_q_180', name: '달리는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 180 }, desc: '180회 완료.' },
    { id: 't_q_200', name: '철저한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 200 }, desc: '200회 완료.' },
    { id: 't_q_250', name: '정확한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 250 }, desc: '250회 완료.' },
    { id: 't_q_300', name: '쉴 틈 없는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 300 }, desc: '300회 완료.' },
    { id: 't_q_350', name: '맹렬한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 350 }, desc: '350회 완료.' },
    { id: 't_q_400', name: '강력한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 400 }, desc: '400회 완료.' },
    { id: 't_q_450', name: '끈질긴', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 450 }, desc: '450회 완료.' },
    { id: 't_q_500', name: '기계적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 500 }, desc: '500회 완료.' },
    { id: 't_q_600', name: '폭발적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 600 }, desc: '600회 완료.' },
    { id: 't_q_700', name: '멈추지 않는', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 700 }, desc: '700회 완료.' },
    { id: 't_q_777', name: '잭팟', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 777 }, desc: '777회 완료.' },
    { id: 't_q_800', name: '정교한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 800 }, desc: '800회 완료.' },
    { id: 't_q_900', name: '완벽한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 900 }, desc: '900회 완료.' },
    { id: 't_q_1000', name: '신속한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 1000 }, desc: '1,000회 완료.' },
    { id: 't_q_1200', name: '놀라운', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 1200 }, desc: '1,200회 완료.' },
    { id: 't_q_1500', name: '극한의', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 1500 }, desc: '1,500회 완료.' },
    { id: 't_q_2000', name: '경이로운', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 2000 }, desc: '2,000회 완료.' },
    { id: 't_q_2500', name: '무시무시한', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 2500 }, desc: '2,500회 완료.' },
    { id: 't_q_3000', name: '전설의', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 3000 }, desc: '3,000회 완료.' },
    { id: 't_q_3500', name: '신화적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 3500 }, desc: '3,500회 완료.' },
    { id: 't_q_4000', name: '헌신적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 4000 }, desc: '4,000회 완료.' },
    { id: 't_q_4500', name: '영웅적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 4500 }, desc: '4,500회 완료.' },
    { id: 't_q_5000', name: '중독된', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 5000 }, desc: '5,000회 완료.' },
    { id: 't_q_6000', name: '체계적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 6000 }, desc: '6,000회 완료.' },
    { id: 't_q_7000', name: '압도적인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 7000 }, desc: '7,000회 완료.' },
    { id: 't_q_8000', name: '초월적', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 8000 }, desc: '8,000회 완료.' },
    { id: 't_q_9000', name: '신의 대행자', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 9000 }, desc: '9,000회 완료.' },
    { id: 't_q_9999', name: '종결된', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 9999 }, desc: '9,999회 완료.' },

    // [GOLD] 재력 (1K ~ 100M) - 25종
    { id: 't_g_1', name: '알뜰한', condition: { type: 'gold', value: 1000 }, desc: '1,000G.' },
    { id: 't_g_2', name: '소박한', condition: { type: 'gold', value: 3000 }, desc: '3,000G.' },
    { id: 't_g_3', name: '절약하는', condition: { type: 'gold', value: 5000 }, desc: '5,000G.' },
    { id: 't_g_4', name: '든든한', condition: { type: 'gold', value: 10000 }, desc: '1만G.' },
    { id: 't_g_5', name: '안정적인', condition: { type: 'gold', value: 20000 }, desc: '2만G.' },
    { id: 't_g_6', name: '여유로운', condition: { type: 'gold', value: 30000 }, desc: '3만G.' },
    { id: 't_g_7', name: '넉넉한', condition: { type: 'gold', value: 50000 }, desc: '5만G.' },
    { id: 't_g_8', name: '풍족한', condition: { type: 'gold', value: 70000 }, desc: '7만G.' },
    { id: 't_g_9', name: '부유한', condition: { type: 'gold', value: 100000 }, desc: '10만G.' },
    { id: 't_g_10', name: '저축하는', condition: { type: 'gold', value: 200000 }, desc: '20만G.' },
    { id: 't_g_11', name: '투자하는', condition: { type: 'gold', value: 300000 }, desc: '30만G.' },
    { id: 't_g_12', name: '사치스러운', condition: { type: 'gold', value: 500000 }, desc: '50만G.' },
    { id: 't_g_13', name: '호화로운', condition: { type: 'gold', value: 700000 }, desc: '70만G.' },
    { id: 't_g_14', name: '성공한', condition: { type: 'gold', value: 1000000 }, desc: '100만G.' },
    { id: 't_g_15', name: '재력가', condition: { type: 'gold', value: 2000000 }, desc: '200만G.' },
    { id: 't_g_16', name: 'VIP', condition: { type: 'gold', value: 3000000 }, desc: '300만G.' },
    { id: 't_g_17', name: 'VVIP', condition: { type: 'gold', value: 5000000 }, desc: '500만G.' },
    { id: 't_g_18', name: '큰손', condition: { type: 'gold', value: 7000000 }, desc: '700만G.' },
    { id: 't_g_19', name: '천만장자', condition: { type: 'gold', value: 10000000 }, desc: '1,000만G.' },
    { id: 't_g_20', name: '부호', condition: { type: 'gold', value: 20000000 }, desc: '2,000만G.' },
    { id: 't_g_21', name: '거부', condition: { type: 'gold', value: 30000000 }, desc: '3,000만G.' },
    { id: 't_g_22', name: '재벌급', condition: { type: 'gold', value: 50000000 }, desc: '5,000만G.' },
    { id: 't_g_23', name: '회장님', condition: { type: 'gold', value: 70000000 }, desc: '7,000만G.' },
    { id: 't_g_24', name: '억만장자', condition: { type: 'gold', value: 100000000 }, desc: '1억G.' },
    { id: 't_g_25', name: '만수르', condition: { type: 'gold', value: 1000000000 }, desc: '10억G.' },

    // [SHOP] 상점 이용 (1~1000회) - 30종
    { id: 't_s_1', name: '첫 쇼핑을 한', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 1 }, desc: '첫 구매.' },
    { id: 't_s_3', name: '관심 있는', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 3 }, desc: '3회 구매.' },
    { id: 't_s_5', name: '맛을 들인', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 5 }, desc: '5회 구매.' },
    { id: 't_s_7', name: '기분파', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 7 }, desc: '7회 구매.' },
    { id: 't_s_10', name: '단골이 된', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 10 }, desc: '10회 구매.' },
    { id: 't_s_15', name: '자주 오는', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 15 }, desc: '15회 구매.' },
    { id: 't_s_20', name: '소비를 즐기는', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 20 }, desc: '20회 구매.' },
    { id: 't_s_25', name: '쇼핑왕', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 25 }, desc: '25회 구매.' },
    { id: 't_s_30', name: '지갑이 얇은', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 30 }, desc: '30회 구매.' },
    { id: 't_s_40', name: '포인트 부자', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 40 }, desc: '40회 구매.' },
    { id: 't_s_50', name: '큰손인', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 50 }, desc: '50회 구매.' },
    { id: 't_s_60', name: '물욕이 많은', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 60 }, desc: '60회 구매.' },
    { id: 't_s_70', name: '수집가', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 70 }, desc: '70회 구매.' },
    { id: 't_s_77', name: '럭키 쇼퍼', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 77 }, desc: '77회 구매.' },
    { id: 't_s_80', name: 'VIP', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 80 }, desc: '80회 구매.' },
    { id: 't_s_90', name: 'VVIP', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 90 }, desc: '90회 구매.' },
    { id: 't_s_100', name: '블랙 컨슈머', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 100 }, desc: '100회 구매.' },
    { id: 't_s_150', name: '쇼핑 중독', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 150 }, desc: '150회 구매.' },
    { id: 't_s_200', name: '창고가 꽉 찬', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 200 }, desc: '200회 구매.' },
    { id: 't_s_300', name: '맥시멀리스트', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 300 }, desc: '300회 구매.' },
    { id: 't_s_400', name: '다 사는', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 400 }, desc: '400회 구매.' },
    { id: 't_s_500', name: '상점주인', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 500 }, desc: '500회 구매.' },
    { id: 't_s_600', name: '재고 정리하는', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 600 }, desc: '600회 구매.' },
    { id: 't_s_700', name: '싹쓸이하는', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 700 }, desc: '700회 구매.' },
    { id: 't_s_800', name: '공급책', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 800 }, desc: '800회 구매.' },
    { id: 't_s_900', name: '도매상', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 900 }, desc: '900회 구매.' },
    { id: 't_s_1000', name: '물류센터', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 1000 }, desc: '1000회 구매.' },

    // [STAT] 스탯별 칭호 (20단계씩 5종 = 100종)
    // STR
    { id: 't_str_1', name: '건강한', condition: { type: 'stat_val', key: 'STR', value: 5 }, desc: 'STR 5' },
    { id: 't_str_2', name: '힘센', condition: { type: 'stat_val', key: 'STR', value: 10 }, desc: 'STR 10' },
    { id: 't_str_3', name: '다부진', condition: { type: 'stat_val', key: 'STR', value: 15 }, desc: 'STR 15' },
    { id: 't_str_4', name: '단단한', condition: { type: 'stat_val', key: 'STR', value: 20 }, desc: 'STR 20' },
    { id: 't_str_5', name: '질긴', condition: { type: 'stat_val', key: 'STR', value: 25 }, desc: 'STR 25' },
    { id: 't_str_6', name: '근육질의', condition: { type: 'stat_val', key: 'STR', value: 30 }, desc: 'STR 30' },
    { id: 't_str_7', name: '강인한', condition: { type: 'stat_val', key: 'STR', value: 35 }, desc: 'STR 35' },
    { id: 't_str_8', name: '우람한', condition: { type: 'stat_val', key: 'STR', value: 40 }, desc: 'STR 40' },
    { id: 't_str_9', name: '강력한', condition: { type: 'stat_val', key: 'STR', value: 45 }, desc: 'STR 45' },
    { id: 't_str_10', name: '무시무시한', condition: { type: 'stat_val', key: 'STR', value: 50 }, desc: 'STR 50' },
    { id: 't_str_11', name: '폭발적인', condition: { type: 'stat_val', key: 'STR', value: 60 }, desc: 'STR 60' },
    { id: 't_str_12', name: '위협적인', condition: { type: 'stat_val', key: 'STR', value: 70 }, desc: 'STR 70' },
    { id: 't_str_13', name: '파괴적인', condition: { type: 'stat_val', key: 'STR', value: 80 }, desc: 'STR 80' },
    { id: 't_str_14', name: '압도적인', condition: { type: 'stat_val', key: 'STR', value: 90 }, desc: 'STR 90' },
    { id: 't_str_15', name: '괴력의', condition: { type: 'stat_val', key: 'STR', value: 100 }, desc: 'STR 100' },
    { id: 't_str_16', name: '거대한', condition: { type: 'stat_val', key: 'STR', value: 200 }, desc: 'STR 200' },
    { id: 't_str_17', name: '초월적인', condition: { type: 'stat_val', key: 'STR', value: 300 }, desc: 'STR 300' },
    { id: 't_str_18', name: '지상을 부수는', condition: { type: 'stat_val', key: 'STR', value: 500 }, desc: 'STR 500' },
    { id: 't_str_19', name: '하늘을 찢는', condition: { type: 'stat_val', key: 'STR', value: 700 }, desc: 'STR 700' },
    { id: 't_str_20', name: '절대적인', condition: { type: 'stat_val', key: 'STR', value: 1000 }, desc: 'STR 1000' },
    // INT
    { id: 't_int_1', name: '생각하는', condition: { type: 'stat_val', key: 'INT', value: 5 }, desc: 'INT 5' },
    { id: 't_int_2', name: '똑똑한', condition: { type: 'stat_val', key: 'INT', value: 10 }, desc: 'INT 10' },
    { id: 't_int_3', name: '총명한', condition: { type: 'stat_val', key: 'INT', value: 15 }, desc: 'INT 15' },
    { id: 't_int_4', name: '영리한', condition: { type: 'stat_val', key: 'INT', value: 20 }, desc: 'INT 20' },
    { id: 't_int_5', name: '비상한', condition: { type: 'stat_val', key: 'INT', value: 25 }, desc: 'INT 25' },
    { id: 't_int_6', name: '현명한', condition: { type: 'stat_val', key: 'INT', value: 30 }, desc: 'INT 30' },
    { id: 't_int_7', name: '논리적인', condition: { type: 'stat_val', key: 'INT', value: 35 }, desc: 'INT 35' },
    { id: 't_int_8', name: '박학다식한', condition: { type: 'stat_val', key: 'INT', value: 40 }, desc: 'INT 40' },
    { id: 't_int_9', name: '지적인', condition: { type: 'stat_val', key: 'INT', value: 45 }, desc: 'INT 45' },
    { id: 't_int_10', name: '뇌섹남인', condition: { type: 'stat_val', key: 'INT', value: 50 }, desc: 'INT 50' },
    { id: 't_int_11', name: '해박한', condition: { type: 'stat_val', key: 'INT', value: 60 }, desc: 'INT 60' },
    { id: 't_int_12', name: '예리한', condition: { type: 'stat_val', key: 'INT', value: 70 }, desc: 'INT 70' },
    { id: 't_int_13', name: '명석한', condition: { type: 'stat_val', key: 'INT', value: 80 }, desc: 'INT 80' },
    { id: 't_int_14', name: '통찰력 있는', condition: { type: 'stat_val', key: 'INT', value: 90 }, desc: 'INT 90' },
    { id: 't_int_15', name: '천재적인', condition: { type: 'stat_val', key: 'INT', value: 100 }, desc: 'INT 100' },
    { id: 't_int_16', name: '마법 같은', condition: { type: 'stat_val', key: 'INT', value: 200 }, desc: 'INT 200' },
    { id: 't_int_17', name: '선구적인', condition: { type: 'stat_val', key: 'INT', value: 300 }, desc: 'INT 300' },
    { id: 't_int_18', name: '우주적인', condition: { type: 'stat_val', key: 'INT', value: 500 }, desc: 'INT 500' },
    { id: 't_int_19', name: '근원의', condition: { type: 'stat_val', key: 'INT', value: 700 }, desc: 'INT 700' },
    { id: 't_int_20', name: '전지전능한', condition: { type: 'stat_val', key: 'INT', value: 1000 }, desc: 'INT 1000' },
    // DEX
    { id: 't_dex_1', name: '꼼꼼한', condition: { type: 'stat_val', key: 'DEX', value: 5 }, desc: 'DEX 5' },
    { id: 't_dex_2', name: '섬세한', condition: { type: 'stat_val', key: 'DEX', value: 10 }, desc: 'DEX 10' },
    { id: 't_dex_3', name: '재주꾼인', condition: { type: 'stat_val', key: 'DEX', value: 15 }, desc: 'DEX 15' },
    { id: 't_dex_4', name: '손재주 좋은', condition: { type: 'stat_val', key: 'DEX', value: 20 }, desc: 'DEX 20' },
    { id: 't_dex_5', name: '감각적인', condition: { type: 'stat_val', key: 'DEX', value: 25 }, desc: 'DEX 25' },
    { id: 't_dex_6', name: '능숙한', condition: { type: 'stat_val', key: 'DEX', value: 30 }, desc: 'DEX 30' },
    { id: 't_dex_7', name: '정교한', condition: { type: 'stat_val', key: 'DEX', value: 35 }, desc: 'DEX 35' },
    { id: 't_dex_8', name: '민첩한', condition: { type: 'stat_val', key: 'DEX', value: 40 }, desc: 'DEX 40' },
    { id: 't_dex_9', name: '빈틈없는', condition: { type: 'stat_val', key: 'DEX', value: 45 }, desc: 'DEX 45' },
    { id: 't_dex_10', name: '신의 손을 가진', condition: { type: 'stat_val', key: 'DEX', value: 50 }, desc: 'DEX 50' },
    { id: 't_dex_11', name: '기술적인', condition: { type: 'stat_val', key: 'DEX', value: 60 }, desc: 'DEX 60' },
    { id: 't_dex_12', name: '기계적인', condition: { type: 'stat_val', key: 'DEX', value: 70 }, desc: 'DEX 70' },
    { id: 't_dex_13', name: '예술적인', condition: { type: 'stat_val', key: 'DEX', value: 80 }, desc: 'DEX 80' },
    { id: 't_dex_14', name: '경이로운', condition: { type: 'stat_val', key: 'DEX', value: 90 }, desc: 'DEX 90' },
    { id: 't_dex_15', name: '마에스트로의', condition: { type: 'stat_val', key: 'DEX', value: 100 }, desc: 'DEX 100' },
    { id: 't_dex_16', name: '기적적인', condition: { type: 'stat_val', key: 'DEX', value: 200 }, desc: 'DEX 200' },
    { id: 't_dex_17', name: '창조적인', condition: { type: 'stat_val', key: 'DEX', value: 300 }, desc: 'DEX 300' },
    { id: 't_dex_18', name: '현실 조작의', condition: { type: 'stat_val', key: 'DEX', value: 500 }, desc: 'DEX 500' },
    { id: 't_dex_19', name: '시공간의', condition: { type: 'stat_val', key: 'DEX', value: 700 }, desc: 'DEX 700' },
    { id: 't_dex_20', name: '절대 감각의', condition: { type: 'stat_val', key: 'DEX', value: 1000 }, desc: 'DEX 1000' },
    // VIT
    { id: 't_vit_1', name: '생기 있는', condition: { type: 'stat_val', key: 'VIT', value: 5 }, desc: 'VIT 5' },
    { id: 't_vit_2', name: '건강한', condition: { type: 'stat_val', key: 'VIT', value: 10 }, desc: 'VIT 10' },
    { id: 't_vit_3', name: '튼튼한', condition: { type: 'stat_val', key: 'VIT', value: 15 }, desc: 'VIT 15' },
    { id: 't_vit_4', name: '질긴', condition: { type: 'stat_val', key: 'VIT', value: 20 }, desc: 'VIT 20' },
    { id: 't_vit_5', name: '활력 넘치는', condition: { type: 'stat_val', key: 'VIT', value: 25 }, desc: 'VIT 25' },
    { id: 't_vit_6', name: '팔팔한', condition: { type: 'stat_val', key: 'VIT', value: 30 }, desc: 'VIT 30' },
    { id: 't_vit_7', name: '강철 같은', condition: { type: 'stat_val', key: 'VIT', value: 35 }, desc: 'VIT 35' },
    { id: 't_vit_8', name: '단단한', condition: { type: 'stat_val', key: 'VIT', value: 40 }, desc: 'VIT 40' },
    { id: 't_vit_9', name: '에너자이저인', condition: { type: 'stat_val', key: 'VIT', value: 45 }, desc: 'VIT 45' },
    { id: 't_vit_10', name: '불사신 같은', condition: { type: 'stat_val', key: 'VIT', value: 50 }, desc: 'VIT 50' },
    { id: 't_vit_11', name: '지치지 않는', condition: { type: 'stat_val', key: 'VIT', value: 60 }, desc: 'VIT 60' },
    { id: 't_vit_12', name: '죽지 않는', condition: { type: 'stat_val', key: 'VIT', value: 70 }, desc: 'VIT 70' },
    { id: 't_vit_13', name: '금강불괴의', condition: { type: 'stat_val', key: 'VIT', value: 80 }, desc: 'VIT 80' },
    { id: 't_vit_14', name: '무적의', condition: { type: 'stat_val', key: 'VIT', value: 90 }, desc: 'VIT 90' },
    { id: 't_vit_15', name: '불멸의', condition: { type: 'stat_val', key: 'VIT', value: 100 }, desc: 'VIT 100' },
    { id: 't_vit_16', name: '머리가 9개인', condition: { type: 'stat_val', key: 'VIT', value: 200 }, desc: 'VIT 200' },
    { id: 't_vit_17', name: '대지의', condition: { type: 'stat_val', key: 'VIT', value: 300 }, desc: 'VIT 300' },
    { id: 't_vit_18', name: '우주의 생명력을 가진', condition: { type: 'stat_val', key: 'VIT', value: 500 }, desc: 'VIT 500' },
    { id: 't_vit_19', name: '영원한', condition: { type: 'stat_val', key: 'VIT', value: 700 }, desc: 'VIT 700' },
    { id: 't_vit_20', name: '절대 생명의', condition: { type: 'stat_val', key: 'VIT', value: 1000 }, desc: 'VIT 1000' },
    // WIS
    { id: 't_wis_1', name: '차분한', condition: { type: 'stat_val', key: 'WIS', value: 5 }, desc: 'WIS 5' },
    { id: 't_wis_2', name: '침착한', condition: { type: 'stat_val', key: 'WIS', value: 10 }, desc: 'WIS 10' },
    { id: 't_wis_3', name: '사려 깊은', condition: { type: 'stat_val', key: 'WIS', value: 15 }, desc: 'WIS 15' },
    { id: 't_wis_4', name: '속 깊은', condition: { type: 'stat_val', key: 'WIS', value: 20 }, desc: 'WIS 20' },
    { id: 't_wis_5', name: '현명한', condition: { type: 'stat_val', key: 'WIS', value: 25 }, desc: 'WIS 25' },
    { id: 't_wis_6', name: '통찰력 있는', condition: { type: 'stat_val', key: 'WIS', value: 30 }, desc: 'WIS 30' },
    { id: 't_wis_7', name: '철학적인', condition: { type: 'stat_val', key: 'WIS', value: 35 }, desc: 'WIS 35' },
    { id: 't_wis_8', name: '멘탈 갑인', condition: { type: 'stat_val', key: 'WIS', value: 40 }, desc: 'WIS 40' },
    { id: 't_wis_9', name: '강철 멘탈의', condition: { type: 'stat_val', key: 'WIS', value: 45 }, desc: 'WIS 45' },
    { id: 't_wis_10', name: '도 닦는', condition: { type: 'stat_val', key: 'WIS', value: 50 }, desc: 'WIS 50' },
    { id: 't_wis_11', name: '고승 같은', condition: { type: 'stat_val', key: 'WIS', value: 60 }, desc: 'WIS 60' },
    { id: 't_wis_12', name: '해탈한', condition: { type: 'stat_val', key: 'WIS', value: 70 }, desc: 'WIS 70' },
    { id: 't_wis_13', name: '성스러운', condition: { type: 'stat_val', key: 'WIS', value: 80 }, desc: 'WIS 80' },
    { id: 't_wis_14', name: '초월적인', condition: { type: 'stat_val', key: 'WIS', value: 90 }, desc: 'WIS 90' },
    { id: 't_wis_15', name: '절대 정신의', condition: { type: 'stat_val', key: 'WIS', value: 100 }, desc: 'WIS 100' },
    { id: 't_wis_16', name: '자비로운', condition: { type: 'stat_val', key: 'WIS', value: 200 }, desc: 'WIS 200' },
    { id: 't_wis_17', name: '순수한', condition: { type: 'stat_val', key: 'WIS', value: 300 }, desc: 'WIS 300' },
    { id: 't_wis_18', name: '근원적인', condition: { type: 'stat_val', key: 'WIS', value: 500 }, desc: 'WIS 500' },
    { id: 't_wis_19', name: '우주의', condition: { type: 'stat_val', key: 'WIS', value: 700 }, desc: 'WIS 700' },
    { id: 't_wis_20', name: '의지적인', condition: { type: 'stat_val', key: 'WIS', value: 1000 }, desc: 'WIS 1000' },

    // [HIDDEN/FUN/USER] 예능, 밈, 맞춤형 (120종 이상)
    { id: 't_h_beg_1', name: '무일푼의', condition: { type: 'stat_max', key: 'gold', value: 10, minLevel: 5 }, desc: '[히든] 전 재산 10원. (Lv.5+)' },
    { id: 't_h_beg_2', name: '빈털터리', condition: { type: 'stat_max', key: 'gold', value: 100, minLevel: 10 }, desc: '[히든] 지갑이 텅텅. (Lv.10+)' },
    { id: 't_h_miser', name: '자린고비의', condition: { type: 'stat_count_less', category: 'shop', key: 'goldSpent', value: 0, minLevel: 30 }, desc: '[히든] Lv.30까지 소비 0원.' },
    { id: 't_h_yolo', name: '탕진잼인', condition: { type: 'stat_count', category: 'shop', key: 'goldSpent', value: 50000 }, desc: '[히든] 번 돈은 바로 씁니다.' },
    { id: 't_h_flex', name: '플렉스하는', condition: { type: 'stat_count', category: 'shop', key: 'goldSpent', value: 100000 }, desc: '[히든] 돈 자랑.' },
    { id: 't_h_vamp', name: '흡혈귀 같은', condition: { type: 'custom_ratio', category: 'quest', key: 'nightOwl', totalKey: 'completed', ratio: 0.9, min: 20 }, desc: '[히든] 밤에만 활동.' },
    { id: 't_h_dawn', name: '새벽반인', condition: { type: 'custom_ratio', category: 'quest', key: 'nightOwl', totalKey: 'completed', ratio: 0.5, min: 20 }, desc: '[히든] 어둠의 자식.' },
    { id: 't_h_morn', name: '바른생활의', condition: { type: 'custom_ratio_low', category: 'quest', key: 'nightOwl', totalKey: 'completed', ratio: 0.1, min: 30 }, desc: '[히든] 밤엔 잡니다.' },
    { id: 't_h_sto', name: '돌머리인', condition: { type: 'stat_max', key: 'INT', value: 3, minLevel: 30 }, desc: '[히든] 몸이 고생함. (Lv.30+, INT 3↓)' },
    { id: 't_h_bir', name: '붕어 기억력의', condition: { type: 'stat_max', key: 'INT', value: 10, minLevel: 30 }, desc: '[히든] 3초 기억. (Lv.30+, INT 10↓)' },
    { id: 't_h_pap', name: '종이인형의', condition: { type: 'stat_max', key: 'VIT', value: 3, minLevel: 30 }, desc: '[히든] 바람 불면 위험. (Lv.30+, VIT 3↓)' },
    { id: 't_h_tur', name: '굼뱅이 같은', condition: { type: 'stat_max', key: 'DEX', value: 3, minLevel: 30 }, desc: '[히든] 느릿느릿. (Lv.30+, DEX 3↓)' },
    { id: 't_h_anc', name: '멸치 같은', condition: { type: 'stat_max', key: 'STR', value: 5, minLevel: 30 }, desc: '[히든] 근육 0%.' },
    { id: 't_h_gla', name: '유리대포의', condition: { type: 'stat_skew', main: 'STR', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 극딜러.' },
    { id: 't_h_mus', name: '근육뇌인', condition: { type: 'stat_skew', main: 'STR', val: 100, otherMax: 10, minLevel: 120 }, desc: '[히든] 뇌 대신 근육.' },
    { id: 't_h_ner', name: '방구석 여포인', condition: { type: 'stat_skew', main: 'INT', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 키보드 최강자.' },
    { id: 't_h_thi', name: '소매치기 같은', condition: { type: 'stat_skew', main: 'DEX', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 손재주 몰빵.' },
    { id: 't_h_tan', name: '샌드백 같은', condition: { type: 'stat_skew', main: 'VIT', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 맷집 몰빵.' },
    { id: 't_h_hex', name: '육각형의', condition: { type: 'stat_balance', val: 40, gap: 5 }, desc: '[히든] 완벽한 밸런스.' },
    { id: 't_h_per', name: '완벽주의적인', condition: { type: 'stat_balance', val: 10, gap: 0 }, desc: '[히든] 모든 스탯이 같음.' },
    { id: 't_h_bit', name: '비트코인 홀더인', condition: { type: 'stat_val', key: 'gold', value: 100000 }, desc: '가즈아!' },
    { id: 't_h_sol', name: '솔라나 풀매수한', condition: { type: 'stat_val', key: 'DEX', value: 40 }, desc: '빠른 전송 속도.' },
    { id: 't_h_eth', name: '이더리움 고래인', condition: { type: 'stat_val', key: 'INT', value: 40 }, desc: '스마트 컨트랙트.' },
    { id: 't_h_xrp', name: '리플 승소 기다리는', condition: { type: 'stat_val', key: 'WIS', value: 40 }, desc: '무한한 인내.' },
    { id: 't_h_hod', name: '존버하는', condition: { type: 'stat_val', key: 'gold', value: 1000000 }, desc: '승리자.' },
    { id: 't_h_liq', name: '청산 당할 뻔한', condition: { type: 'stat_max', key: 'gold', value: 1, minLevel: 50 }, desc: '[히든] 아찔했습니다.' },
    { id: 't_h_pia', name: '쇼팽을 꿈꾸는', condition: { type: 'stat_val', key: 'DEX', value: 30 }, desc: '피아노 연주자.' },
    { id: 't_h_adhd', name: '도파민 중독된', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 1 }, desc: '첫 도파민.' },
    { id: 't_h_lun', name: '월급 루팡인', condition: { type: 'custom_ratio_low', category: 'quest', key: 'completed', totalKey: 'completed', ratio: 0.1, min: 10 }, desc: '[히든] 농땡이 전문가.' },
    { id: 't_h_protein', name: '단백질 도둑인', condition: { type: 'stat_val', key: 'STR', value: 60 }, desc: '내 닭가슴살 돌려내.' },
    { id: 't_h_coffee', name: '카페인 전사인', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 44 }, desc: '커피로 연명 중.' },
    { id: 't_h_delivery', name: '배달 VIP인', condition: { type: 'gold', value: 50000 }, desc: '배달비가 아깝지 않아.' },
    { id: 't_h_lucky7', name: '럭키 세븐인', condition: { type: 'total_level', value: 77 }, desc: '777을 향해.' },
    { id: 't_h_devil6', name: '악마 같은', condition: { type: 'total_level', value: 66 }, desc: '666.' },
    { id: 't_h_angel1', name: '천사 같은', condition: { type: 'total_level', value: 104 }, desc: '1004.' },
    { id: 't_h_solo', name: '철벽의 솔로인', condition: { type: 'stat_val', key: 'WIS', value: 50 }, desc: '[히든] 멘탈이 강해졌습니다.' },
    { id: 't_h_nomad', name: '디지털 노마드인', condition: { type: 'stat_sum', keys: ['INT', 'WIS', 'DEX'], value: 120 }, desc: '어디서든 작업.' },
    { id: 't_h_keyboard', name: '키보드 워리어인', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 50 }, desc: '타자가 빠름.' },
    { id: 't_h_bed', name: '침대 점령군인', condition: { type: 'stat_max', key: 'STR', value: 1, minLevel: 10 }, desc: '[히든] 눕는 게 제일 좋아.' },
    { id: 't_h_gym', name: '헬스장 기부왕인', condition: { type: 'stat_max', key: 'STR', value: 5, minLevel: 40 }, desc: '[히든] 돈만 냄.' },
    { id: 't_h_chaos', name: '혼돈의 파괴자인', condition: { type: 'stat_balance', val: 5, gap: 50 }, desc: '[히든] 스탯 불균형 끝판왕.' },
    { id: 't_h_shhh', name: '사서 고생하는', condition: { type: 'stat_val', key: 'WIS', value: 20 }, desc: '왜 그랬을까.' },
    { id: 't_h_sugar', name: '액상과당 중독인', condition: { type: 'stat_val', key: 'VIT', value: 15 }, desc: '달달함이 최고.' },
    { id: 't_h_netflix', name: '정주행 고수인', condition: { type: 'stat_max', key: 'DEX', value: 10, minLevel: 20 }, desc: '주말 순삭.' },
    { id: 't_h_delivery_2', name: '배민 단골인', condition: { type: 'gold', value: 70000 }, desc: '배달 최고.' },
    { id: 't_h_snack', name: '야식 매니아인', condition: { type: 'custom_ratio', category: 'quest', key: 'nightOwl', totalKey: 'completed', ratio: 0.5, min: 10 }, desc: '밤에 먹어야 제맛.' },
    { id: 't_h_procr', name: '미루기 대장인', condition: { type: 'total_level', value: 1 }, desc: '내일부터 할게요.' },
    { id: 't_h_perfect', name: '칼 같은', condition: { type: 'stat_balance', val: 10, gap: 0 }, desc: '[히든] 오차 0.' },
    { id: 't_h_history', name: '살아있는 역사인', condition: { type: 'total_level', value: 1000 }, desc: '1000시간.' },
    { id: 't_h_myth', name: '신화가 된', condition: { type: 'total_level', value: 5000 }, desc: '전설 그 이상.' },
    { id: 't_h_legend', name: '레전드 그 자체인', condition: { type: 'total_level', value: 9999 }, desc: '시스템의 정점.' },
    { id: 't_h_piano_master', name: '리스트를 꿈꾸는', condition: { type: 'stat_val', key: 'DEX', value: 60 }, desc: '초절기교.' },
    { id: 't_h_back_pain', name: '허리가 쑤시는', condition: { type: 'stat_val', key: 'VIT', value: 1 }, desc: '앉아있기 힘듦.' },
    { id: 't_h_crypto_rich', name: '수익률 1000%의', condition: { type: 'gold', value: 2000000 }, desc: '익절은 지능순.' },
    { id: 't_h_crypto_poor', name: '수익률 -99%의', condition: { type: 'stat_max', key: 'gold', value: 10, minLevel: 30 }, desc: '[히든] 상폐 주의.' },
    { id: 't_h_mac_user', name: '매킨토시 쓰는', condition: { type: 'stat_val', key: 'DEX', value: 25 }, desc: '감성 컨트롤.' },
    { id: 't_h_python_dev', name: '파이썬에 진심인', condition: { type: 'stat_val', key: 'INT', value: 35 }, desc: 'import antigravity.' },
    { id: 't_h_gym_rat', name: '쇠 냄새 맡는', condition: { type: 'stat_val', key: 'STR', value: 85 }, desc: '3대 500 돌파.' },
    { id: 't_h_library', name: '책 냄새 좋아하는', condition: { type: 'stat_val', key: 'INT', value: 75 }, desc: '도서관 지박령.' },
    { id: 't_h_owl_2', name: '밤을 지새운', condition: { type: 'stat_count', category: 'quest', key: 'nightOwl', value: 100 }, desc: '불면증.' },
    { id: 't_h_morn_2', name: '조찬 모임 나가는', condition: { type: 'custom_ratio_low', category: 'quest', key: 'nightOwl', totalKey: 'completed', ratio: 0.05, min: 100 }, desc: '아침형 인간 2단계.' },
    { id: 't_h_balance_master', name: '중도를 걷는', condition: { type: 'stat_balance', val: 100, gap: 3 }, desc: '중심이 잡혔습니다.' },
    { id: 't_h_all_rounder', name: '못하는 게 없는', condition: { type: 'stat_balance', val: 70, gap: 10 }, desc: '다능인.' },
    { id: 't_h_expert_1', name: '이름값 하는', condition: { type: 'count_unlocked', target: 'title', value: 50 }, desc: '칭호 50개 보유.' },
    { id: 't_h_expert_2', name: '칭호 수집가인', condition: { type: 'count_unlocked', target: 'title', value: 150 }, desc: '칭호 150개 보유.' },
    { id: 't_h_job_master', name: '이직의 달인인', condition: { type: 'count_unlocked', target: 'job', value: 50 }, desc: '직업 50개 보유.' },
    { id: 't_h_final_boss', name: '최종 보스 같은', condition: { type: 'total_level', value: 7777 }, desc: '포스가 남다름.' }
];


// =============================================================================
// 🛠️ JOB DATA (직업: 명사, 역할, 사회적 신분) - 380종
// =============================================================================
export const JOB_DATA = [
    { id: 'j_null', name: '무직', condition: null, desc: '아직 사회적 자아를 찾지 못했습니다.' },

    // STR (힘) (Tier 1 ~ 30)
    { id: 'j_s_1', name: '짐꾼', condition: { type: 'stat_val', key: 'STR', value: 5 }, desc: 'Lv.5 | 무거운 짐을 나릅니다.' },
    { id: 'j_s_2', name: '막노동꾼', condition: { type: 'stat_val', key: 'STR', value: 8 }, desc: 'Lv.8 | 현장의 일꾼.' },
    { id: 'j_s_3', name: '견습생', condition: { type: 'stat_val', key: 'STR', value: 10 }, desc: 'Lv.10 | 운동 시작.' },
    { id: 'j_s_4', name: '운동보조', condition: { type: 'stat_val', key: 'STR', value: 13 }, desc: 'Lv.13 | 덤벨 셔틀.' },
    { id: 'j_s_5', name: '헬스 초보', condition: { type: 'stat_val', key: 'STR', value: 15 }, desc: 'Lv.15 | 헬린이 입성.' },
    { id: 'j_s_6', name: '보디가드', condition: { type: 'stat_val', key: 'STR', value: 20 }, desc: 'Lv.20 | 의뢰인 보호.' },
    { id: 'j_s_7', name: '아마추어 복서', condition: { type: 'stat_val', key: 'STR', value: 25 }, desc: 'Lv.25 | 스파링 가능.' },
    { id: 'j_s_8', name: '프로 운동선수', condition: { type: 'stat_val', key: 'STR', value: 30 }, desc: 'Lv.30 | 지역구 대표.' },
    { id: 'j_s_9', name: '돌격병', condition: { type: 'stat_val', key: 'STR', value: 35 }, desc: 'Lv.35 | 최전방 보병.' },
    { id: 'j_s_10', name: '돌격대장', condition: { type: 'stat_val', key: 'STR', value: 40 }, desc: 'Lv.40 | 기동대장.' },
    { id: 'j_s_11', name: '트레이너', condition: { type: 'stat_val', key: 'STR', value: 45 }, desc: 'Lv.45 | 식단 체크 시작.' },
    { id: 'j_s_12', name: '언더아머단', condition: { type: 'stat_val', key: 'STR', value: 50 }, desc: 'Lv.50 | 3대 500 달성.' },
    { id: 'j_s_13', name: '용병', condition: { type: 'stat_val', key: 'STR', value: 60 }, desc: 'Lv.60 | 전장의 해결사.' },
    { id: 'j_s_14', name: '보디빌더', condition: { type: 'stat_val', key: 'STR', value: 70 }, desc: 'Lv.70 | 조각된 육체.' },
    { id: 'j_s_15', name: '장사', condition: { type: 'stat_val', key: 'STR', value: 80 }, desc: 'Lv.80 | 힘이 장사.' },
    { id: 'j_s_16', name: '천하장사', condition: { type: 'stat_val', key: 'STR', value: 90 }, desc: 'Lv.90 | 황소를 던짐.' },
    { id: 'j_s_17', name: '글래디에이터', condition: { type: 'stat_val', key: 'STR', value: 100 }, desc: 'Lv.100 | 투기장의 왕.' },
    { id: 'j_s_18', name: '챔피언', condition: { type: 'stat_val', key: 'STR', value: 120 }, desc: 'Lv.120 | 패배를 모름.' },
    { id: 'j_s_19', name: '스트롱맨', condition: { type: 'stat_val', key: 'STR', value: 150 }, desc: 'Lv.150 | 기차를 끕니다.' },
    { id: 'j_s_20', name: '강철의 거인', condition: { type: 'stat_val', key: 'STR', value: 200 }, desc: 'Lv.200 | 몸이 강철.' },
    { id: 'j_s_21', name: '바바리안', condition: { type: 'stat_val', key: 'STR', value: 250 }, desc: 'Lv.250 | 야성.' },
    { id: 'j_s_22', name: '헐크', condition: { type: 'stat_val', key: 'STR', value: 300 }, desc: 'Lv.300 | 초록 괴물.' },
    { id: 'j_s_23', name: '타이탄', condition: { type: 'stat_val', key: 'STR', value: 400 }, desc: 'Lv.400 | 거인.' },
    { id: 'j_s_24', name: '헤라클레스', condition: { type: 'stat_val', key: 'STR', value: 500 }, desc: 'Lv.500 | 영웅.' },
    { id: 'j_s_25', name: '반신', condition: { type: 'stat_val', key: 'STR', value: 700 }, desc: 'Lv.700 | 신의 아들.' },
    { id: 'j_s_26', name: '아수라', condition: { type: 'stat_val', key: 'STR', value: 900 }, desc: 'Lv.900 | 투신.' },
    { id: 'j_s_27', name: '전쟁의 신', condition: { type: 'stat_val', key: 'STR', value: 1000 }, desc: 'Lv.1000 | 아레스.' },
    { id: 'j_s_28', name: '파괴신', condition: { type: 'stat_val', key: 'STR', value: 2000 }, desc: 'Lv.2000 | 멸망.' },
    { id: 'j_s_29', name: '행성 파괴자', condition: { type: 'stat_val', key: 'STR', value: 5000 }, desc: 'Lv.5000 | 타노스.' },
    { id: 'j_s_30', name: '절대 무력', condition: { type: 'stat_val', key: 'STR', value: 10000 }, desc: 'Lv.10000 | 끝.' },

    // INT (지능) (Tier 1 ~ 30)
    { id: 'j_i_1', name: '학생', condition: { type: 'stat_val', key: 'INT', value: 5 }, desc: 'Lv.5 | 공부 시작.' },
    { id: 'j_i_2', name: '서기', condition: { type: 'stat_val', key: 'INT', value: 8 }, desc: 'Lv.8 | 기록 담당.' },
    { id: 'j_i_3', name: '모범생', condition: { type: 'stat_val', key: 'INT', value: 10 }, desc: 'Lv.10 | 우등생.' },
    { id: 'j_i_4', name: '독서광', condition: { type: 'stat_val', key: 'INT', value: 13 }, desc: 'Lv.13 | 활자 중독.' },
    { id: 'j_i_5', name: '학예사', condition: { type: 'stat_val', key: 'INT', value: 15 }, desc: 'Lv.15 | 지식 정리.' },
    { id: 'j_i_6', name: '장학생', condition: { type: 'stat_val', key: 'INT', value: 20 }, desc: 'Lv.20 | 1등.' },
    { id: 'j_i_7', name: '연구보조', condition: { type: 'stat_val', key: 'INT', value: 25 }, desc: 'Lv.25 | 조수.' },
    { id: 'j_i_8', name: '연구원', condition: { type: 'stat_val', key: 'INT', value: 30 }, desc: 'Lv.30 | 데이터 분석.' },
    { id: 'j_i_9', name: '대학생', condition: { type: 'stat_val', key: 'INT', value: 35 }, desc: 'Lv.35 | 전공 공부.' },
    { id: 'j_i_10', name: '대학원생', condition: { type: 'stat_val', key: 'INT', value: 40 }, desc: 'Lv.40 | 랩실 망령.' },
    { id: 'j_i_11', name: '석사', condition: { type: 'stat_val', key: 'INT', value: 45 }, desc: 'Lv.45 | 전문 지식.' },
    { id: 'j_i_12', name: '박사', condition: { type: 'stat_val', key: 'INT', value: 50 }, desc: 'Lv.50 | 학문의 길.' },
    { id: 'j_i_13', name: '수석 연구원', condition: { type: 'stat_val', key: 'INT', value: 60 }, desc: 'Lv.60 | 연구소장.' },
    { id: 'j_i_14', name: '교수', condition: { type: 'stat_val', key: 'INT', value: 70 }, desc: 'Lv.70 | 강단 교육.' },
    { id: 'j_i_15', name: '학자', condition: { type: 'stat_val', key: 'INT', value: 80 }, desc: 'Lv.80 | 지식 탐구.' },
    { id: 'j_i_16', name: '천재', condition: { type: 'stat_val', key: 'INT', value: 90 }, desc: 'Lv.90 | IQ 150+.' },
    { id: 'j_i_17', name: '석학', condition: { type: 'stat_val', key: 'INT', value: 100 }, desc: 'Lv.100 | 인류의 지성.' },
    { id: 'j_i_18', name: '지휘관', condition: { type: 'stat_val', key: 'INT', value: 120 }, desc: 'Lv.120 | 전술가.' },
    { id: 'j_i_19', name: '대현자', condition: { type: 'stat_val', key: 'INT', value: 150 }, desc: 'Lv.150 | 현자.' },
    { id: 'j_i_20', name: '예언자', condition: { type: 'stat_val', key: 'INT', value: 200 }, desc: 'Lv.200 | 미래 계산.' },
    { id: 'j_i_21', name: '마도 공학자', condition: { type: 'stat_val', key: 'INT', value: 300 }, desc: 'Lv.300 | 마법 과학.' },
    { id: 'j_i_22', name: '아카식 레코드', condition: { type: 'stat_val', key: 'INT', value: 400 }, desc: 'Lv.400 | 정보 저장소.' },
    { id: 'j_i_23', name: '지식의 신', condition: { type: 'stat_val', key: 'INT', value: 500 }, desc: 'Lv.500 | 토트.' },
    { id: 'j_i_24', name: '진리 탐구자', condition: { type: 'stat_val', key: 'INT', value: 700 }, desc: 'Lv.700 | 진리.' },
    { id: 'j_i_25', name: '라플라스의 악마', condition: { type: 'stat_val', key: 'INT', value: 1000 }, desc: 'Lv.1000 | 인과율.' },
    { id: 'j_i_26', name: '초월적 지성', condition: { type: 'stat_val', key: 'INT', value: 2000 }, desc: 'Lv.2000 | 차원 이해.' },
    { id: 'j_i_27', name: '우주의 의지', condition: { type: 'stat_val', key: 'INT', value: 3000 }, desc: 'Lv.3000 | 섭리.' },
    { id: 'j_i_28', name: '지성체', condition: { type: 'stat_val', key: 'INT', value: 5000 }, desc: 'Lv.5000 | 정신체.' },
    { id: 'j_i_29', name: '절대 지능', condition: { type: 'stat_val', key: 'INT', value: 8000 }, desc: 'Lv.8000 | 초지능.' },
    { id: 'j_i_30', name: '전지전능', condition: { type: 'stat_val', key: 'INT', value: 10000 }, desc: 'Lv.10000 | 신.' },

    // DEX (솜씨) (Tier 1 ~ 30)
    { id: 'j_d_1', name: '수습생', condition: { type: 'stat_val', key: 'DEX', value: 5 }, desc: 'Lv.5 | 망치질.' },
    { id: 'j_d_2', name: '기능공', condition: { type: 'stat_val', key: 'DEX', value: 8 }, desc: 'Lv.8 | 연장 사용.' },
    { id: 'j_d_3', name: '조립공', condition: { type: 'stat_val', key: 'DEX', value: 10 }, desc: 'Lv.10 | 조립 숙련.' },
    { id: 'j_d_4', name: '수리공', condition: { type: 'stat_val', key: 'DEX', value: 13 }, desc: 'Lv.13 | 고칩니다.' },
    { id: 'j_d_5', name: '정밀 작업자', condition: { type: 'stat_val', key: 'DEX', value: 15 }, desc: 'Lv.15 | 섬세함.' },
    { id: 'j_d_6', name: '조각가', condition: { type: 'stat_val', key: 'DEX', value: 20 }, desc: 'Lv.20 | 모양을 냄.' },
    { id: 'j_d_7', name: '기술자', condition: { type: 'stat_val', key: 'DEX', value: 25 }, desc: 'Lv.25 | 전문 수리.' },
    { id: 'j_d_8', name: '시계공', condition: { type: 'stat_val', key: 'DEX', value: 30 }, desc: 'Lv.30 | 미세 조작.' },
    { id: 'j_d_9', name: '엔지니어', condition: { type: 'stat_val', key: 'DEX', value: 35 }, desc: 'Lv.35 | 설계.' },
    { id: 'j_d_10', name: '정비사', condition: { type: 'stat_val', key: 'DEX', value: 40 }, desc: 'Lv.40 | 기계 전문가.' },
    { id: 'j_d_11', name: '예술가', condition: { type: 'stat_val', key: 'DEX', value: 45 }, desc: 'Lv.45 | 예술 창조.' },
    { id: 'j_d_12', name: '금손', condition: { type: 'stat_val', key: 'DEX', value: 50 }, desc: 'Lv.50 | 신의 손길.' },
    { id: 'j_d_13', name: '연금술사', condition: { type: 'stat_val', key: 'DEX', value: 60 }, desc: 'Lv.60 | 물질 변환.' },
    { id: 'j_d_14', name: '스나이퍼', condition: { type: 'stat_val', key: 'DEX', value: 70 }, desc: 'Lv.70 | 정확한 저격.' },
    { id: 'j_d_15', name: '장인', condition: { type: 'stat_val', key: 'DEX', value: 80 }, desc: 'Lv.80 | 달인의 경지.' },
    { id: 'j_d_16', name: '명장', condition: { type: 'stat_val', key: 'DEX', value: 90 }, desc: 'Lv.90 | 국보급.' },
    { id: 'j_d_17', name: '인간 문화재', condition: { type: 'stat_val', key: 'DEX', value: 100 }, desc: 'Lv.100 | 살아있는 역사.' },
    { id: 'j_d_18', name: '마에스트로', condition: { type: 'stat_val', key: 'DEX', value: 120 }, desc: 'Lv.120 | 거장.' },
    { id: 'j_d_19', name: '기계신', condition: { type: 'stat_val', key: 'DEX', value: 150 }, desc: 'Lv.150 | 기계 조종.' },
    { id: 'j_d_20', name: '나노 마스터', condition: { type: 'stat_val', key: 'DEX', value: 200 }, desc: 'Lv.200 | 원자 단위.' },
    { id: 'j_d_21', name: '데미갓', condition: { type: 'stat_val', key: 'DEX', value: 300 }, desc: 'Lv.300 | 신의 조작.' },
    { id: 'j_d_22', name: '창조주', condition: { type: 'stat_val', key: 'DEX', value: 400 }, desc: 'Lv.400 | 세상 조각.' },
    { id: 'j_d_23', name: '현실 조작자', condition: { type: 'stat_val', key: 'DEX', value: 500 }, desc: 'Lv.500 | 매트릭스.' },
    { id: 'j_d_24', name: '차원 조각가', condition: { type: 'stat_val', key: 'DEX', value: 700 }, desc: 'Lv.700 | 시공간 설계.' },
    { id: 'j_d_25', name: '우주 설계자', condition: { type: 'stat_val', key: 'DEX', value: 1000 }, desc: 'Lv.1000 | 성계 디자이너.' },
    { id: 'j_d_26', name: '법칙 파괴자', condition: { type: 'stat_val', key: 'DEX', value: 2000 }, desc: 'Lv.2000 | 물리법칙 수정.' },
    { id: 'j_d_27', name: '절대 창조주', condition: { type: 'stat_val', key: 'DEX', value: 3000 }, desc: 'Lv.3000 | 존재를 구현.' },
    { id: 'j_d_28', name: '관측자', condition: { type: 'stat_val', key: 'DEX', value: 5000 }, desc: 'Lv.5000 | 보는 대로 변함.' },
    { id: 'j_d_29', name: '절대 감각', condition: { type: 'stat_val', key: 'DEX', value: 8000 }, desc: 'Lv.8000 | 만물의 조작.' },
    { id: 'j_d_30', name: '공허의 조각가', condition: { type: 'stat_val', key: 'DEX', value: 10000 }, desc: 'Lv.10000 | 무를 유로.' },

    // VIT (체력) (Tier 1 ~ 30)
    { id: 'j_v_1', name: '산책러', condition: { type: 'stat_val', key: 'VIT', value: 5 }, desc: 'Lv.5 | 가벼운 걷기.' },
    { id: 'j_v_2', name: '보행자', condition: { type: 'stat_val', key: 'VIT', value: 8 }, desc: 'Lv.8 | 튼튼한 다리.' },
    { id: 'j_v_3', name: '등산객', condition: { type: 'stat_val', key: 'VIT', value: 10 }, desc: 'Lv.10 | 야호!' },
    { id: 'j_v_4', name: '조깅러', condition: { type: 'stat_val', key: 'VIT', value: 13 }, desc: 'Lv.13 | 러닝.' },
    { id: 'j_v_5', name: '마라토너', condition: { type: 'stat_val', key: 'VIT', value: 15 }, desc: 'Lv.15 | 42.195km.' },
    { id: 'j_v_6', name: '생존가', condition: { type: 'stat_val', key: 'VIT', value: 20 }, desc: 'Lv.20 | 생존 기술.' },
    { id: 'j_v_7', name: '야생아', condition: { type: 'stat_val', key: 'VIT', value: 25 }, desc: 'Lv.25 | 적응력.' },
    { id: 'j_v_8', name: '에너자이저', condition: { type: 'stat_val', key: 'VIT', value: 30 }, desc: 'Lv.30 | 지치지 않음.' },
    { id: 'j_v_9', name: '철인', condition: { type: 'stat_val', key: 'VIT', value: 35 }, desc: 'Lv.35 | 3종 경기.' },
    { id: 'j_v_10', name: '탱커', condition: { type: 'stat_val', key: 'VIT', value: 40 }, desc: 'Lv.40 | 방패 담당.' },
    { id: 'j_v_11', name: '수호자', condition: { type: 'stat_val', key: 'VIT', value: 50 }, desc: 'Lv.50 | 가디언.' },
    { id: 'j_v_12', name: '강철인간', condition: { type: 'stat_val', key: 'VIT', value: 60 }, desc: 'Lv.60 | 오토메일.' },
    { id: 'j_v_13', name: '불사신', condition: { type: 'stat_val', key: 'VIT', value: 70 }, desc: 'Lv.70 | 좀비 체력.' },
    { id: 'j_v_14', name: '금강불괴', condition: { type: 'stat_val', key: 'VIT', value: 80 }, desc: 'Lv.80 | 무적의 몸.' },
    { id: 'j_v_15', name: '트롤', condition: { type: 'stat_val', key: 'VIT', value: 90 }, desc: 'Lv.90 | 초재생.' },
    { id: 'j_v_16', name: '피닉스', condition: { type: 'stat_val', key: 'VIT', value: 100 }, desc: 'Lv.100 | 부활.' },
    { id: 'j_v_17', name: '불멸자', condition: { type: 'stat_val', key: 'VIT', value: 150 }, desc: 'Lv.150 | 죽지 않음.' },
    { id: 'j_v_18', name: '뱀파이어 로드', condition: { type: 'stat_val', key: 'VIT', value: 200 }, desc: 'Lv.200 | 영생.' },
    { id: 'j_v_19', name: '드래곤', condition: { type: 'stat_val', key: 'VIT', value: 300 }, desc: 'Lv.300 | 최강 생물.' },
    { id: 'j_v_20', name: '히드라', condition: { type: 'stat_val', key: 'VIT', value: 400 }, desc: 'Lv.400 | 머리가 아홉.' },
    { id: 'j_v_21', name: '리바이어던', condition: { type: 'stat_val', key: 'VIT', value: 500 }, desc: 'Lv.500 | 해수.' },
    { id: 'j_v_22', name: '가이아', condition: { type: 'stat_val', key: 'VIT', value: 700 }, desc: 'Lv.700 | 대지.' },
    { id: 'j_v_23', name: '행성 포식자', condition: { type: 'stat_val', key: 'VIT', value: 1000 }, desc: 'Lv.1000 | 별을 먹음.' },
    { id: 'j_v_24', name: '코즈믹 엔티티', condition: { type: 'stat_val', key: 'VIT', value: 2000 }, desc: 'Lv.2000 | 공포.' },
    { id: 'j_v_25', name: '우주적 존재', condition: { type: 'stat_val', key: 'VIT', value: 3000 }, desc: 'Lv.3000 | 실체 없음.' },
    { id: 'j_v_26', name: '집합 생명체', condition: { type: 'stat_val', key: 'VIT', value: 4000 }, desc: 'Lv.4000 | 군단.' },
    { id: 'j_v_27', name: '불멸의 신', condition: { type: 'stat_val', key: 'VIT', value: 5000 }, desc: 'Lv.5000 | 이모탈 갓.' },
    { id: 'j_v_28', name: '영원', condition: { type: 'stat_val', key: 'VIT', value: 7000 }, desc: 'Lv.7000 | 시간 무시.' },
    { id: 'j_v_29', name: '엔트로피', condition: { type: 'stat_val', key: 'VIT', value: 9000 }, desc: 'Lv.9000 | 무질서.' },
    { id: 'j_v_30', name: '절대 생명', condition: { type: 'stat_val', key: 'VIT', value: 10000 }, desc: 'Lv.10000 | 영생 그 자체.' },

    // WIS (지혜) (Tier 1 ~ 30)
    { id: 'j_w_1', name: '사색가', condition: { type: 'stat_val', key: 'WIS', value: 5 }, desc: 'Lv.5 | 생각.' },
    { id: 'j_w_2', name: '성찰가', condition: { type: 'stat_val', key: 'WIS', value: 8 }, desc: 'Lv.8 | 나를 본다.' },
    { id: 'j_w_3', name: '조언가', condition: { type: 'stat_val', key: 'WIS', value: 10 }, desc: 'Lv.10 | 조언.' },
    { id: 'j_w_4', name: '상담사', condition: { type: 'stat_val', key: 'WIS', value: 13 }, desc: 'Lv.13 | 경청.' },
    { id: 'j_w_5', name: '심리상담사', condition: { type: 'stat_val', key: 'WIS', value: 15 }, desc: 'Lv.15 | 치유.' },
    { id: 'j_w_6', name: '수도승', condition: { type: 'stat_val', key: 'WIS', value: 20 }, desc: 'Lv.20 | 비움.' },
    { id: 'j_w_7', name: '수도자', condition: { type: 'stat_val', key: 'WIS', value: 25 }, desc: 'Lv.25 | 수양.' },
    { id: 'j_w_8', name: '철학자', condition: { type: 'stat_val', key: 'WIS', value: 30 }, desc: 'Lv.30 | 질문.' },
    { id: 'j_w_9', name: '사상가', condition: { type: 'stat_val', key: 'WIS', value: 35 }, desc: 'Lv.35 | 체계화.' },
    { id: 'j_w_10', name: '심리학자', condition: { type: 'stat_val', key: 'WIS', value: 40 }, desc: 'Lv.40 | 분석.' },
    { id: 'j_w_11', name: '멘탈코치', condition: { type: 'stat_val', key: 'WIS', value: 45 }, desc: 'Lv.45 | 케어.' },
    { id: 'j_w_12', name: '정신분석가', condition: { type: 'stat_val', key: 'WIS', value: 50 }, desc: 'Lv.50 | 심층.' },
    { id: 'j_w_13', name: '구도자', condition: { type: 'stat_val', key: 'WIS', value: 60 }, desc: 'Lv.60 | 진리.' },
    { id: 'j_w_14', name: '고승', condition: { type: 'stat_val', key: 'WIS', value: 70 }, desc: 'Lv.70 | 도인.' },
    { id: 'j_w_15', name: '현자', condition: { type: 'stat_val', key: 'WIS', value: 80 }, desc: 'Lv.80 | 지혜.' },
    { id: 'j_w_16', name: '대사제', condition: { type: 'stat_val', key: 'WIS', value: 90 }, desc: 'Lv.90 | 비숍.' },
    { id: 'j_w_17', name: '성인', condition: { type: 'stat_val', key: 'WIS', value: 100 }, desc: 'Lv.100 | 세인트.' },
    { id: 'j_w_18', name: '교황', condition: { type: 'stat_val', key: 'WIS', value: 120 }, desc: 'Lv.120 | 지도자.' },
    { id: 'j_w_19', name: '해탈자', condition: { type: 'stat_val', key: 'WIS', value: 150 }, desc: 'Lv.150 | 초월.' },
    { id: 'j_w_20', name: '메시아', condition: { type: 'stat_val', key: 'WIS', value: 200 }, desc: 'Lv.200 | 구원.' },
    { id: 'j_w_21', name: '천사', condition: { type: 'stat_val', key: 'WIS', value: 300 }, desc: 'Lv.300 | 사자.' },
    { id: 'j_w_22', name: '세라핌', condition: { type: 'stat_val', key: 'WIS', value: 400 }, desc: 'Lv.400 | 치천사.' },
    { id: 'j_w_23', name: '지혜의 신', condition: { type: 'stat_val', key: 'WIS', value: 500 }, desc: 'Lv.500 | 아테나.' },
    { id: 'j_w_24', name: '운명의 관측자', condition: { type: 'stat_val', key: 'WIS', value: 700 }, desc: 'Lv.700 | 운명.' },
    { id: 'j_w_25', name: '절대 정신', condition: { type: 'stat_val', key: 'WIS', value: 1000 }, desc: 'Lv.1000 | 이데아.' },
    { id: 'j_w_26', name: '아카샤', condition: { type: 'stat_val', key: 'WIS', value: 2000 }, desc: 'Lv.2000 | 허공.' },
    { id: 'j_w_27', name: '너바나', condition: { type: 'stat_val', key: 'WIS', value: 3000 }, desc: 'Lv.3000 | 열반.' },
    { id: 'j_w_28', name: '옴니', condition: { type: 'stat_val', key: 'WIS', value: 5000 }, desc: 'Lv.5000 | 모든 것.' },
    { id: 'j_w_29', name: '우주의 의지', condition: { type: 'stat_val', key: 'WIS', value: 8000 }, desc: 'Lv.8000 | 코스모스.' },
    { id: 'j_w_30', name: '절대자', condition: { type: 'stat_val', key: 'WIS', value: 10000 }, desc: 'Lv.10000 | The One.' },

    // =========================================================================
    // 6. 하이브리드 (복합 스탯) - 50종
    // =========================================================================
    { id: 'j_h_si_1', name: '전술가', condition: { type: 'stat_sum', keys: ['STR','INT'], value: 40 }, desc: '힘+지능.' },
    { id: 'j_h_si_2', name: '지휘관', condition: { type: 'stat_sum', keys: ['STR','INT'], value: 100 }, desc: '리더.' },
    { id: 'j_h_si_3', name: '마검사', condition: { type: 'stat_sum', keys: ['STR','INT'], value: 200 }, desc: '검성.' },
    { id: 'j_h_sd_1', name: '싸움꾼', condition: { type: 'stat_sum', keys: ['STR','DEX'], value: 40 }, desc: '힘+솜씨.' },
    { id: 'j_h_sd_2', name: '무도가', condition: { type: 'stat_sum', keys: ['STR','DEX'], value: 100 }, desc: '권법가.' },
    { id: 'j_h_sd_3', name: '웨폰마스터', condition: { type: 'stat_sum', keys: ['STR','DEX'], value: 200 }, desc: '병기 창고.' },
    { id: 'j_h_sv_1', name: '돌격병', condition: { type: 'stat_sum', keys: ['STR','VIT'], value: 40 }, desc: '힘+체력.' },
    { id: 'j_h_sv_2', name: '광전사', condition: { type: 'stat_sum', keys: ['STR','VIT'], value: 100 }, desc: '버서커.' },
    { id: 'j_h_sv_3', name: '워로드', condition: { type: 'stat_sum', keys: ['STR','VIT'], value: 200 }, desc: '군주.' },
    { id: 'j_h_id_1', name: '설계자', condition: { type: 'stat_sum', keys: ['INT','DEX'], value: 40 }, desc: '지능+솜씨.' },
    { id: 'j_h_id_2', name: '발명가', condition: { type: 'stat_sum', keys: ['INT','DEX'], value: 100 }, desc: '에디슨.' },
    { id: 'j_h_id_3', name: '연금술사', condition: { type: 'stat_sum', keys: ['INT','DEX'], value: 200 }, desc: '강철.' },
    { id: 'j_h_iw_1', name: '학자', condition: { type: 'stat_sum', keys: ['INT','WIS'], value: 40 }, desc: '지능+지혜.' },
    { id: 'j_h_iw_2', name: '대현자', condition: { type: 'stat_sum', keys: ['INT','WIS'], value: 100 }, desc: '통찰.' },
    { id: 'j_h_iw_3', name: '아크메이지', condition: { type: 'stat_sum', keys: ['INT','WIS'], value: 200 }, desc: '마법 정점.' },
    { id: 'j_h_dv_1', name: '탐험가', condition: { type: 'stat_sum', keys: ['DEX','VIT'], value: 40 }, desc: '솜씨+체력.' },
    { id: 'j_h_dv_2', name: '레인저', condition: { type: 'stat_sum', keys: ['DEX','VIT'], value: 100 }, desc: '추적자.' },
    { id: 'j_h_dv_3', name: '비스트 마스터', condition: { type: 'stat_sum', keys: ['DEX','VIT'], value: 200 }, desc: '야수 지배.' },
    { id: 'j_h_sw_1', name: '수호기사', condition: { type: 'stat_sum', keys: ['STR','WIS'], value: 40 }, desc: '힘+지혜.' },
    { id: 'j_h_sw_2', name: '성기사', condition: { type: 'stat_sum', keys: ['STR','WIS'], value: 100 }, desc: '팔라딘.' },
    { id: 'j_h_sw_3', name: '크루세이더', condition: { type: 'stat_sum', keys: ['STR','WIS'], value: 200 }, desc: '심판관.' },
    { id: 'j_h_dw_1', name: '수도사', condition: { type: 'stat_sum', keys: ['DEX','WIS'], value: 40 }, desc: '솜씨+지혜.' },
    { id: 'j_h_dw_2', name: '몽크', condition: { type: 'stat_sum', keys: ['DEX','WIS'], value: 100 }, desc: '조화.' },
    { id: 'j_h_dw_3', name: '신선', condition: { type: 'stat_sum', keys: ['DEX','WIS'], value: 200 }, desc: '안개.' },
    { id: 'j_h_vw_1', name: '드루이드', condition: { type: 'stat_sum', keys: ['VIT','WIS'], value: 40 }, desc: '체력+지혜.' },
    { id: 'j_h_vw_2', name: '샤먼', condition: { type: 'stat_sum', keys: ['VIT','WIS'], value: 100 }, desc: '정령.' },
    { id: 'j_h_vw_3', name: '가디언', condition: { type: 'stat_sum', keys: ['VIT','WIS'], value: 200 }, desc: '세상의 방패.' },
    { id: 'j_h_iv_1', name: '전투마법사', condition: { type: 'stat_sum', keys: ['INT','VIT'], value: 40 }, desc: '마법 탱커.' },
    { id: 'j_h_iv_2', name: '워록', condition: { type: 'stat_sum', keys: ['INT','VIT'], value: 100 }, desc: '흑마법사.' },
    { id: 'j_h_iv_3', name: '리치', condition: { type: 'stat_sum', keys: ['INT','VIT'], value: 200 }, desc: '불사 마법.' },

    // =========================================================================
    // 7. 현대 & 특수 & 예능 (150종 이상)
    // =========================================================================
    { id: 'j_m_1', name: '소비자', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 1 }, desc: '첫 구매.' },
    { id: 'j_m_2', name: '코인 트레이더', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 40 }, desc: '차트 분석.' },
    { id: 'j_m_3', name: '퀀트 투자자', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 60 }, desc: '알고리즘 매매.' },
    { id: 'j_m_4', name: '전업 투자자', condition: { type: 'stat_val', key: 'gold', value: 1000000 }, desc: '100만G 돌파.' },
    { id: 'j_m_5', name: '피아니스트', condition: { type: 'stat_val', key: 'DEX', value: 30 }, desc: '건반 위의 마술.' },
    { id: 'j_m_6', name: '회장님', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 100 }, desc: '리더십.' },
    { id: 'j_m_7', name: '백테스터', condition: { type: 'stat_val', key: 'INT', value: 45 }, desc: '과거 분석.' },
    { id: 'j_m_8', name: '도파민 중독자', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 1 }, desc: '쇼츠 중독.' },
    { id: 'j_m_9', name: '생산성 귀신', condition: { type: 'stat_sum', keys: ['INT', 'WIS', 'VIT'], value: 90 }, desc: 'LLG 최적화.' },
    { id: 'j_m_10', name: '서버장', condition: { type: 'stat_val', key: 'INT', value: 33 }, desc: '안 터지게 관리.' },
    { id: 'j_m_11', name: '프로게이머', condition: { type: 'stat_sum', keys: ['DEX', 'INT'], value: 80 }, desc: 'APM 400.' },
    { id: 'j_m_12', name: '스트리머', condition: { type: 'stat_val', key: 'WIS', value: 40 }, desc: '방송 중.' },
    { id: 'j_m_13', name: '유튜버', condition: { type: 'stat_sum', keys: ['DEX', 'WIS'], value: 55 }, desc: '구독과 좋아요.' },
    { id: 'j_m_14', name: '인플루언서', condition: { type: 'stat_val', key: 'WIS', value: 65 }, desc: '광고 협찬.' },
    { id: 'j_m_15', name: 'CEO', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 150 }, desc: '대표이사.' },
    { id: 'j_m_16', name: '개발자', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 95 }, desc: '코딩 노예.' },
    { id: 'j_m_17', name: '의사', condition: { type: 'stat_sum', keys: ['INT', 'VIT'], value: 120 }, desc: '힐러.' },
    { id: 'j_m_18', name: '변호사', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 115 }, desc: '법적 해결.' },
    { id: 'j_m_19', name: '작가', condition: { type: 'stat_val', key: 'INT', value: 65 }, desc: '마감의 공포.' },
    { id: 'j_m_20', name: '경찰', condition: { type: 'stat_sum', keys: ['STR', 'WIS'], value: 85 }, desc: '정의 구현.' },
    { id: 'j_m_21', name: '소방관', condition: { type: 'stat_sum', keys: ['STR', 'VIT'], value: 95 }, desc: '영웅.' },
    { id: 'j_m_22', name: '웹툰 작가', condition: { type: 'stat_sum', keys: ['DEX', 'INT'], value: 85 }, desc: '지옥 마감.' },
    { id: 'j_m_23', name: '셰프', condition: { type: 'stat_sum', keys: ['DEX', 'VIT'], value: 75 }, desc: '맛의 대가.' },
    { id: 'j_m_24', name: '파일럿', condition: { type: 'stat_sum', keys: ['DEX', 'INT'], value: 140 }, desc: '비행.' },
    { id: 'j_m_25', name: '농부', condition: { type: 'stat_sum', keys: ['STR', 'VIT'], value: 65 }, desc: '농심.' },
    { id: 'j_m_26', name: '어부', condition: { type: 'stat_sum', keys: ['STR', 'DEX'], value: 70 }, desc: '만선.' },
    { id: 'j_m_27', name: '광부', condition: { type: 'stat_sum', keys: ['STR', 'VIT'], value: 80 }, desc: '채굴.' },
    { id: 'j_m_28', name: '해커', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 130 }, desc: '뚫습니다.' },
    { id: 'j_m_29', name: '스파이', condition: { type: 'stat_sum', keys: ['DEX', 'WIS'], value: 125 }, desc: '비밀.' },
    { id: 'j_m_30', name: '제빵사', condition: { type: 'stat_sum', keys: ['DEX', 'VIT'], value: 68 }, desc: '빵굽.' },
    { id: 'j_m_31', name: '기자', condition: { type: 'stat_sum', keys: ['INT', 'VIT'], value: 85 }, desc: '특종.' },
    { id: 'j_m_32', name: '선생님', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 70 }, desc: '참교육.' },
    { id: 'j_m_33', name: '간호사', condition: { type: 'stat_sum', keys: ['VIT', 'WIS'], value: 85 }, desc: '돌봄.' },
    { id: 'j_m_34', name: '약사', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 110 }, desc: '조제.' },
    { id: 'j_m_35', name: '판사', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 190 }, desc: '심판.' },
    { id: 'j_m_36', name: '군인', condition: { type: 'stat_sum', keys: ['STR', 'VIT'], value: 65 }, desc: '충성.' },
    { id: 'j_m_37', name: '모델', condition: { type: 'stat_sum', keys: ['VIT', 'STR'], value: 90 }, desc: '워킹.' },
    { id: 'j_m_38', name: '아이돌', condition: { type: 'stat_balance', val: 55, gap: 10 }, desc: '센터.' },
    { id: 'j_m_39', name: '프로 낚시꾼', condition: { type: 'stat_val', key: 'DEX', value: 44 }, desc: '입질.' },
    { id: 'j_m_40', name: '정원사', condition: { type: 'stat_val', key: 'VIT', value: 24 }, desc: '조경.' },
    { id: 'j_m_41', name: '사서', condition: { type: 'stat_val', key: 'INT', value: 55 }, desc: '조용.' },
    { id: 'j_m_42', name: '건축가', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 105 }, desc: '빌딩.' },
    { id: 'j_m_43', name: '디자이너', condition: { type: 'stat_sum', keys: ['DEX', 'WIS'], value: 95 }, desc: '감각.' },
    { id: 'j_m_44', name: '사진작가', condition: { type: 'stat_sum', keys: ['DEX', 'WIS'], value: 65 }, desc: '찰칵.' },
    { id: 'j_m_45', name: '가수', condition: { type: 'stat_sum', keys: ['VIT', 'WIS'], value: 85 }, desc: '보컬.' },
    { id: 'j_m_46', name: '배우', condition: { type: 'stat_sum', keys: ['DEX', 'WIS'], value: 95 }, desc: '연기.' },
    { id: 'j_m_47', name: '운동권', condition: { type: 'stat_val', key: 'STR', value: 110 }, desc: '파괴.' },
    { id: 'j_m_48', name: '상인', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 75 }, desc: '거상.' },
    { id: 'j_m_49', name: '해적왕', condition: { type: 'stat_sum', keys: ['STR', 'VIT'], value: 150 }, desc: '원피스.' },
    { id: 'j_m_50', name: '용사', condition: { type: 'total_level', value: 777 }, desc: '마왕군.' },
    { id: 'j_m_51', name: '마왕', condition: { type: 'total_level', value: 666 }, desc: '공포.' },
    { id: 'j_m_52', name: '신', condition: { type: 'total_level', value: 10000 }, desc: '절대.' },
    { id: 'j_m_53', name: '뉴비', condition: { type: 'total_level', value: 1 }, desc: '응애.' },
    { id: 'j_m_54', name: '고수', condition: { type: 'total_level', value: 200 }, desc: '고수.' },
    { id: 'j_m_55', name: '초고수', condition: { type: 'total_level', value: 500 }, desc: '초고수.' },
    { id: 'j_m_56', name: '네임드', condition: { type: 'count_unlocked', target: 'title', value: 20 }, desc: '이름값.' },
    { id: 'j_m_57', name: '랭커', condition: { type: 'total_level', value: 800 }, desc: '순위권.' },
    { id: 'j_m_58', name: '지배자', condition: { type: 'total_level', value: 1500 }, desc: '통치.' },
    { id: 'j_m_59', name: '전설', condition: { type: 'total_level', value: 3000 }, desc: '역사.' },
    { id: 'j_m_60', name: '불멸', condition: { type: 'total_level', value: 8000 }, desc: '이모탈.' },
    { id: 'j_m_61', name: '리뷰어', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 10 }, desc: '10회 구매.' },
    { id: 'j_m_62', name: '쇼퍼홀릭', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 50 }, desc: '50회 구매.' },
    { id: 'j_m_63', name: '바리스타', condition: { type: 'stat_sum', keys: ['DEX', 'WIS'], value: 45 }, desc: '커피향.' },
    { id: 'j_m_64', name: '편의점 알바', condition: { type: 'stat_sum', keys: ['STR', 'WIS'], value: 30 }, desc: '야간 근무.' },
    { id: 'j_m_65', name: '택배 기사', condition: { type: 'stat_sum', keys: ['STR', 'VIT'], value: 70 }, desc: '로켓 배송.' },
    { id: 'j_m_66', name: '버스 기사', condition: { type: 'stat_sum', keys: ['DEX', 'VIT'], value: 60 }, desc: '안전 운전.' },
    { id: 'j_m_67', name: '유치원 교사', condition: { type: 'stat_sum', keys: ['WIS', 'VIT'], value: 65 }, desc: '아이들.' },
    { id: 'j_m_68', name: '미용사', condition: { type: 'stat_sum', keys: ['DEX', 'WIS'], value: 55 }, desc: '스타일.' },
    { id: 'j_m_69', name: '통역가', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 90 }, desc: '언어의 장벽.' },
    { id: 'j_m_70', name: '회계사', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 110 }, desc: '숫자 싸움.' },
    { id: 'j_m_71', name: '보안관', condition: { type: 'stat_sum', keys: ['STR', 'INT'], value: 80 }, desc: '보안.' },
    { id: 'j_m_72', name: '탐험가', condition: { type: 'stat_sum', keys: ['VIT', 'WIS'], value: 75 }, desc: '미지의 세계.' },
    { id: 'j_m_73', name: '사육사', condition: { type: 'stat_sum', keys: ['STR', 'WIS'], value: 70 }, desc: '동물 친구.' },
    { id: 'j_m_74', name: '경호원', condition: { type: 'stat_sum', keys: ['STR', 'DEX'], value: 95 }, desc: '보디가드.' },
    { id: 'j_m_75', name: '비서', condition: { type: 'stat_sum', keys: ['INT', 'DEX', 'WIS'], value: 100 }, desc: '일정 관리.' },

    // [Funny/Hidden] (minLevel 적용)
    { id: 'j_fh_1', name: '너드', condition: { type: 'stat_skew', main: 'INT', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 운동 싫어함.' },
    { id: 'j_fh_2', name: '헬창', condition: { type: 'stat_skew', main: 'STR', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 근손실.' },
    { id: 'j_fh_3', name: '도둑', condition: { type: 'stat_skew', main: 'DEX', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 돚거.' },
    { id: 'j_fh_4', name: '좀비', condition: { type: 'stat_skew', main: 'VIT', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 불사.' },
    { id: 'j_fh_5', name: '유령', condition: { type: 'stat_skew', main: 'WIS', val: 50, otherMax: 5, minLevel: 60 }, desc: '[히든] 투명.' },
    { id: 'j_fh_6', name: '백수', condition: { type: 'stat_max', key: 'gold', value: 0, minLevel: 10 }, desc: '[히든] 0G.' },
    { id: 'j_fh_7', name: '건물주', condition: { type: 'gold', value: 10000000 }, desc: '[히든] 부자.' },
    { id: 'j_fh_8', name: '육각형', condition: { type: 'stat_balance', val: 35, gap: 5 }, desc: '[히든] 조화.' },
    { id: 'j_fh_9', name: '인력소장', condition: { type: 'count_unlocked', target: 'job', value: 35 }, desc: '[히든] 수집.' },
    { id: 'j_fh_10', name: '방구석 여포', condition: { type: 'stat_sum', keys: ['INT', 'DEX'], value: 110 }, desc: '[히든] 키배.' },
    { id: 'j_fh_11', name: '단백질 빌런', condition: { type: 'stat_val', key: 'STR', value: 82 }, desc: '[히든] 닭.' },
    { id: 'j_fh_12', name: '알고리즘 노예', condition: { type: 'stat_val', key: 'INT', value: 72 }, desc: '[히든] 유튜브.' },
    { id: 'j_fh_13', name: '월급 루팡', condition: { type: 'stat_max', key: 'STR', value: 2, minLevel: 45 }, desc: '[히든] 꿀.' },
    { id: 'j_fh_14', name: '프로 미루미', condition: { type: 'total_level', value: 1 }, desc: '나중에.' },
    { id: 'j_fh_15', name: '침대 점령군', condition: { type: 'stat_max', key: 'VIT', value: 2, minLevel: 25 }, desc: '[히든] 눕.' },
    { id: 'j_fh_16', name: '카페인 중독자', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 120 }, desc: '커피.' },
    { id: 'j_fh_17', name: '새벽반 회장', condition: { type: 'stat_count', category: 'quest', key: 'nightOwl', value: 60 }, desc: '밤샘.' },
    { id: 'j_fh_18', name: '키보드 마스터', condition: { type: 'stat_val', key: 'DEX', value: 48 }, desc: '타자.' },
    { id: 'j_fh_19', name: '다이아몬드 손', condition: { type: 'stat_val', key: 'WIS', value: 75 }, desc: '존버.' },
    { id: 'j_fh_20', name: '지갑 도둑', condition: { type: 'stat_count', category: 'shop', key: 'goldSpent', value: 300000 }, desc: '지름.' },

    // (보너스 50개 - 다양한 조합과 드립)
    { id: 'j_b_1', name: '키보드 배틀러', condition: { type: 'stat_sum', keys: ['INT', 'WIS'], value: 50 }, desc: '논리 정연한 욕설.' },
    { id: 'j_b_2', name: '비둘기 조련사', condition: { type: 'stat_val', key: 'WIS', value: 12 }, desc: '구구구구.' },
    { id: 'j_b_3', name: '프로 불참러', condition: { type: 'stat_max', key: 'VIT', value: 5, minLevel: 15 }, desc: '조세호.' },
    { id: 'j_b_4', name: '라면 요리사', condition: { type: 'stat_val', key: 'DEX', value: 7 }, desc: '물 조절 장인.' },
    { id: 'j_b_5', name: '프로 퇴근러', condition: { type: 'stat_val', key: 'DEX', value: 55 }, desc: '빛보다 빠른 퇴근.' },
    { id: 'j_b_6', name: '이불 밖은 위험해', condition: { type: 'stat_max', key: 'VIT', value: 4, minLevel: 22 }, desc: '집순이/집돌이.' },
    { id: 'j_b_7', name: '코인 졸업자', condition: { type: 'gold', value: 7000000 }, desc: '한강 뷰.' },
    { id: 'j_b_8', name: '국밥 매니아', condition: { type: 'gold', value: 80000 }, desc: '뜨끈하고 든든하게.' },
    { id: 'j_b_9', name: '아메리카노 중독', condition: { type: 'stat_val', key: 'VIT', value: 11 }, desc: '얼죽아.' },
    { id: 'j_b_10', name: '단백질 쉐이크 장인', condition: { type: 'stat_val', key: 'STR', value: 44 }, desc: '안 뭉치게 섞기.' },
    { id: 'j_b_11', name: '스쿼트 귀신', condition: { type: 'stat_val', key: 'STR', value: 66 }, desc: '하체 비대.' },
    { id: 'j_b_12', name: '프로 숨쉬기 운동가', condition: { type: 'stat_max', key: 'STR', value: 2, minLevel: 5 }, desc: '유일한 운동.' },
    { id: 'j_b_13', name: '데이터 노가다꾼', condition: { type: 'stat_val', key: 'INT', value: 22 }, desc: '단순 반복.' },
    { id: 'j_b_14', name: '엑셀 마스터', condition: { type: 'stat_val', key: 'INT', value: 58 }, desc: 'VLOOKUP.' },
    { id: 'j_b_15', name: 'PPT 장인', condition: { type: 'stat_val', key: 'DEX', value: 42 }, desc: '보여주기식.' },
    { id: 'j_b_16', name: '회의 주재자', condition: { type: 'stat_val', key: 'WIS', value: 33 }, desc: '결론 없음.' },
    { id: 'j_b_17', name: '상상 투자자', condition: { type: 'stat_val', key: 'INT', value: 12, minLevel: 5 }, desc: '살걸 그랬다.' },
    { id: 'j_b_18', name: '멘탈 연금술사', condition: { type: 'stat_val', key: 'WIS', value: 88 }, desc: '부정적 생각 제거.' },
    { id: 'j_b_19', name: '새벽 감성 시인', condition: { type: 'custom_ratio', category: 'quest', key: 'nightOwl', totalKey: 'completed', ratio: 0.7, min: 15 }, desc: '싸이월드 감성.' },
    { id: 'j_b_20', name: '유리 멘탈 보호자', condition: { type: 'stat_max', key: 'WIS', value: 8, minLevel: 10 }, desc: '살살 말해줘.' },
    { id: 'j_b_21', name: '거울 성애자', condition: { type: 'stat_val', key: 'STR', value: 40 }, desc: '오운완 인증.' },
    { id: 'j_b_22', name: '홈트 전문가', condition: { type: 'stat_val', key: 'VIT', value: 28 }, desc: '유튜브 보고 함.' },
    { id: 'j_b_23', name: '장비병 환자', condition: { type: 'stat_count', category: 'shop', key: 'goldSpent', value: 90000 }, desc: '도구가 좋아야 함.' },
    { id: 'j_b_24', name: '아이디어 뱅크', condition: { type: 'stat_val', key: 'INT', value: 68 }, desc: '실행은 안 함.' },
    { id: 'j_b_25', name: '프로 걱정러', condition: { type: 'stat_val', key: 'WIS', value: 25 }, desc: '만약에 말야.' },
    { id: 'j_b_26', name: '현실 도피자', condition: { type: 'total_level', value: 4 }, desc: '잠시만 안녕.' },
    { id: 'j_b_27', name: '도파민 절제기', condition: { type: 'stat_val', key: 'WIS', value: 110 }, desc: '디지털 디톡스.' },
    { id: 'j_b_28', name: '뇌 과부하', condition: { type: 'stat_val', key: 'INT', value: 130 }, desc: '생각 중단.' },
    { id: 'j_b_29', name: '근성 가이', condition: { type: 'stat_val', key: 'VIT', value: 120 }, desc: '안 포기함.' },
    { id: 'j_b_30', name: '동네 형', condition: { type: 'total_level', value: 55 }, desc: '친근함.' },
    { id: 'j_b_31', name: '백과사전', condition: { type: 'stat_val', key: 'INT', value: 140 }, desc: '설명충.' },
    { id: 'j_b_32', name: '프로 리스너', condition: { type: 'stat_val', key: 'WIS', value: 48 }, desc: '응응 그렇구나.' },
    { id: 'j_b_33', name: '손기술 장인', condition: { type: 'stat_val', key: 'DEX', value: 78 }, desc: '펜 돌리기.' },
    { id: 'j_b_34', name: '체력 바보', condition: { type: 'stat_val', key: 'VIT', value: 85, minLevel: 100 }, desc: '잠이 안 옴.' },
    { id: 'j_b_35', name: '멘탈 갑', condition: { type: 'stat_val', key: 'WIS', value: 150 }, desc: '부동심.' },
    { id: 'j_b_36', name: '해결사', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 333 }, desc: '다 고쳐줌.' },
    { id: 'j_b_37', name: '지갑 전사', condition: { type: 'stat_count', category: 'shop', key: 'goldSpent', value: 555555 }, desc: '돈으로 해결.' },
    { id: 'j_b_38', name: '프로 일꾼', condition: { type: 'stat_count', category: 'quest', key: 'completed', value: 555 }, desc: '성실.' },
    { id: 'j_b_39', name: '전설의 용사', condition: { type: 'total_level', value: 7777 }, desc: '신화.' },
    { id: 'j_b_40', name: '동네 이장', condition: { type: 'stat_val', key: 'WIS', value: 35 }, desc: '오지랖.' },
    { id: 'j_b_41', name: '프로 골퍼', condition: { type: 'stat_val', key: 'DEX', value: 52 }, desc: '나이스 샷.' },
    { id: 'j_b_42', name: '테니스 요정', condition: { type: 'stat_val', key: 'STR', value: 38 }, desc: '서브.' },
    { id: 'j_b_43', name: '주짓수 수련생', condition: { type: 'stat_val', key: 'STR', value: 42 }, desc: '탭탭.' },
    { id: 'j_b_44', name: '필라테스 고수', condition: { type: 'stat_val', key: 'VIT', value: 45 }, desc: '속근육.' },
    { id: 'j_b_45', name: '요가 달인', condition: { type: 'stat_val', key: 'WIS', value: 45 }, desc: '유연함.' },
    { id: 'j_b_46', name: '게임 폐인', condition: { type: 'stat_max', key: 'VIT', value: 5, minLevel: 80 }, desc: '[히든] 밤샘 게임.' },
    { id: 'j_b_47', name: '프로 쇼퍼', condition: { type: 'stat_count', category: 'shop', key: 'purchases', value: 77 }, desc: '택배 기다림.' },
    { id: 'j_b_48', name: '미니멀리스트', condition: { type: 'stat_count_less', category: 'shop', key: 'purchases', value: 1, minLevel: 50 }, desc: '[히든] 안 삼.' },
    { id: 'j_b_49', name: '갓생 살기', condition: { type: 'stat_balance', val: 50, gap: 5 }, desc: '부지런한 삶.' },
    { id: 'j_b_50', name: '인생 마스터', condition: { type: 'total_level', value: 2000 }, desc: '다 살았다.' }
];

export const LOOT_TABLE = [];
